### ISSUE TITLE
Getting NoneType Object Not Scriptable when creating new Client

### ISSUE THREAD

**Issue by carTloyal123** [shauntarves/wyze-sdk#110]
When creating new client object with just email and password, python errors and returns the following:

~~~
Traceback (most recent call last):
  File "/home/ctl/devel/homebridge/homebridge-wyze-suite/py_helpers/getThermostatDeviceList.py", line 13, in <module>
    client = Client(email=sys.argv[1], password=os.sys.argv[2])
  File "/home/ctl/.local/lib/python3.10/site-packages/wyze_sdk/api/client.py", line 59, in __init__
    self.login()
  File "/home/ctl/.local/lib/python3.10/site-packages/wyze_sdk/api/client.py", line 139, in login
    response = self._auth_client().user_login(email=self._email, password=self._password, totp_key=self._totp_key)
  File "/home/ctl/.local/lib/python3.10/site-packages/wyze_sdk/service/auth_service.py", line 76, in user_login
    if response['access_token']:
TypeError: 'NoneType' object is not subscriptable
~~~

This seems to be an intermittent issue like sometimes it will happen and sometimes it will work totally fine. Any suggestions welcome and would be good to have for further development.

**Comment by carTloyal123** [comment]
It looks like this is a recurring issue of some sort. Any way to handle this in the background or present an WyzeAPI error instead?

**Comment by shauntarves** [comment]
I can look into this a bit. If you're able to provide some more detail, it might speed things up. Does this account have 2FA enabled? Please run the same code with debugging enabled and share the result:

```
...
wyze_sdk.set_stream_logger('wyze_sdk', level=logging.DEBUG)
client = Client(email=sys.argv[1], password=os.sys.argv[2])
...
```

**Comment by carTloyal123** [comment]
Hey @shauntarves thanks for the reply. Please see the debug output below:

Only redacted the password hash for safety. Please let me know if I should remove other pieces of this as well and if this provides any insight into potential issues.

~~~
[11/28/2022, 10:16:02 AM] [WyzeSuitePlatform] Python ERROR:Error: 2022-11-28 10:16:02,242 [DEBUG] wyze_sdk.api.client: access token not provided, attempting to login as carsonloyal123@me.com
2022-11-28 10:16:02,242 [DEBUG] wyze_sdk.service.base: merging request-specific headers into session headers
2022-11-28 10:16:02,243 [DEBUG] wyze_sdk.service.base: unmodified prepared request
2022-11-28 10:16:02,243 [DEBUG] wyze_sdk.service.base: <PreparedRequest [POST]>
2022-11-28 10:16:02,243 [INFO] wyze_sdk.service.base: requesting POST to https://auth-prod.api.wyze.com/user/login
2022-11-28 10:16:02,243 [DEBUG] wyze_sdk.service.base: headers: {'User-Agent': 'wyze_android_2.19.14', 'Accept-Encoding': 'gzip', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-api-key': 'RckMFKbsds5p6QY3COEXc2ABwNTYY0q18ziEiSEm', 'appid': '9319141212m2ik', 'appinfo': 'wyze_android_2.19.14', 'phoneid': '9ba02389-7603-4c25-a493-74cf3d1d4ab9', 'requestid': '29f1c2d1f34d74e6fb40f01e14934728', 'signature2': 'e6c1510f5f6f4d4114abab215a5802ab', 'Content-Length': '103', 'Content-Type': 'application/json'}
2022-11-28 10:16:02,243 [DEBUG] wyze_sdk.service.base: body: b'{"nonce":"1669652162242","email":"carsonloyal123@me.com","password":"<redacted>"}'
2022-11-28 10:16:02,243 [DEBUG] wyze_sdk.service.base: settings: {'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
Traceback (most recent call last):
  File "/var/lib/homebridge/node_modules/homebridge-wyze-suite/py_helpers/getThermostatDeviceList.py", line 14, in <module>
    client = Client(email=sys.argv[1], password=os.sys.argv[2])
  File "/home/homebridge/.local/lib/python3.10/site-packages/wyze_sdk/api/client.py", line 59, in __init__
    self.login()
  File "/home/homebridge/.local/lib/python3.10/site-packages/wyze_sdk/api/client.py", line 139, in login
    response = self._auth_client().user_login(email=self._email, password=self._password, totp_key=self._totp_key)
  File "/home/homebridge/.local/lib/python3.10/site-packages/wyze_sdk/service/auth_service.py", line 76, in user_login
    if response['access_token']:
TypeError: 'NoneType' object is not subscriptable
~~~

**Comment by shauntarves** [comment]
`client = Client(email=sys.argv[1], password=os.sys.argv[2])`

This line ^^ - is it possible that the password isn't getting properly passed and we're hashing an empty string? A shot in the dark since you have `sys.argv` in one case and `os.sys.argv` in the other.

Ultimately, it seems like the response object is `NoneType`, which I've not seen before, so that leads me to think that the request isn't correct. I can definitely handle this better/differently - it's just a case I've not encountered.

**Comment by guyfromhe** [comment]
I wrote a custom program and the username, pw and 2FA are hardcoded into the client line so nothing is being passed, and mine randomly stops working as well with the same NoneType error... It's been going on for months but I haven't been home to see the actual error or what's going on until now. 

I have a process that keeps restarting the program every few minutes and it usually does this for an hour or two and then starts working again without me touching anything, so I am guessing it's something on the server side that isn't liking what it's sending.

Not sure I can be any more help here, but just wanted to say I'm also able to repro this issue intermittently and it's not just this person.

And just like that the problem went away and my same code is running perfectly again... Hope you can squish this bug.  If there's anything I can do to help let me know... Fortunately (or unfortunately for debugging purposes) it only seems to happen a couple times a month.

**Comment by carTloyal123** [comment]
@guyfromhe thank you for confirming this also happens to you. It definitely seems to be a Wyze thing since I can try to log into the website when this happens and of course I get the same message. I assume a bunch of close together login attempts trigger a security lock on an account that has some arbitrary cool down. It is strange though how it only happens sometimes and not others. I think some of this will be remedied by persistent authentication instead of a fresh login every time a client object is created. As far as this thread goes, possibly just adding an error message for this particular case would be plenty to close this thread. The authentication discussion can continue on #105

**Comment by shauntarves** [comment]
I agree that (on first glance) it's probably some kind of authentication cool down. All the work coming from #105 and #109 to support pre-configuring a client with tokens should make this situation much better.

Hang tight and I'll have something for you all soon!
