### ISSUE TITLE
SDK throws exception on import due to usage on deprecated distutils (python 3.12)

### ISSUE THREAD

**Issue by smartin015** [shauntarves/wyze-sdk#190]
```
python3                         
Python 3.12.7 (main, Oct  1 2024, 02:05:46) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wyze_sdk import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/semartin/Documents/protohaven_api/venv/lib/python3.12/site-packages/wyze_sdk/__init__.py", line 3, in <module>
    from .api import Client  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/semartin/Documents/protohaven_api/venv/lib/python3.12/site-packages/wyze_sdk/api/__init__.py", line 1, in <module>
    from .client import Client  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/semartin/Documents/protohaven_api/venv/lib/python3.12/site-packages/wyze_sdk/api/client.py", line 4, in <module>
    from wyze_sdk.api.base import BaseClient
  File "/home/semartin/Documents/protohaven_api/venv/lib/python3.12/site-packages/wyze_sdk/api/base.py", line 6, in <module>
    from wyze_sdk.models.devices.base import DeviceModels
  File "/home/semartin/Documents/protohaven_api/venv/lib/python3.12/site-packages/wyze_sdk/models/__init__.py", line 5, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils'
```

[Distutils is deprecated](https://docs.python.org/3.10/library/distutils.html) and is removed on python 3.12 and higher.

**Comment by smartin015** [comment]
I've created #191 to eliminate usage of distutils.
