### ISSUE TITLE
Login Failure: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by terrycarlin** [shauntarves/wyze-sdk#52]
This has been working for quite a while without any changes. A few weeks ago it started failing and I haven't changed a thing.
This is basically the same code as the example code from the README pages.
I am able to log onto the wyze app with the same login.

/usr/local/bin/python3.9 /Users/tcarlin/PycharmProjects/wyze-sdk/wyze_devices.py
Traceback (most recent call last):
  File "/Users/tcarlin/PycharmProjects/wyze-sdk/wyze_devices.py", line 7, in <module>
    client = Client(email=os.environ['WYZE_EMAIL'], password=os.environ['WYZE_PASSWORD'])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wyze_sdk/api/client.py", line 59, in __init__
    self.login()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wyze_sdk/api/client.py", line 139, in login
    response = self._auth_client().user_login(email=self._email, password=self._password, totp_key=self._totp_key)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wyze_sdk/service/auth_service.py", line 77, in user_login
    if response['access_token']:
TypeError: 'NoneType' object is not subscriptable

**Comment by WindJunkie** [comment]
FWIW the login is working fine for me today, with a freshly installed SDK. From the error it appears that response is completely empty for you. Any chance this was a temporary issue?

**Comment by terrycarlin** [comment]
It's working now. It was down for a full day. It filled up my syslog file putting a traceback every 15 seconds. Will close.

**Comment by terrycarlin** [comment]
Seems to be a Wyze server error.
