### ISSUE TITLE
Date issue in Scale get_records query

### ISSUE THREAD

**Issue by svanhoutte** [shauntarves/wyze-sdk#60]
Hello 

I m trying to get the get_records working for the scale. when i call the function it seems it doesn't take into account the start_time, i can put anything the result is always the same if provides all the records. When i enter the end_time with it i get and error as bellow :
Traceback (most recent call last):
  File "./scale.py", line 23, in <module>
    print(f"weight: {client.scales.get_records(start_time='2021,12,10',end_time='2021,12,17')}")
  File "/home/efreeze/.local/lib/python3.8/site-packages/wyze_sdk/api/devices/scales.py", line 89, in get_records
    return [ScaleRecord(**record) for record in super()._scale_client().get_records(user_id=user_id if user_id is not None else self._user_id, start_time=start_time, end_time=end_time)["data"]]
  File "/home/efreeze/.local/lib/python3.8/site-packages/wyze_sdk/service/scale_service.py", line 166, in get_records
    kwargs.update({'start_time': str(0), 'end_time': str(datetime_to_epoch(end_time))})
  File "/home/efreeze/.local/lib/python3.8/site-packages/wyze_sdk/models/__init__.py", line 20, in datetime_to_epoch
    return int(datetime.timestamp() * 1000)
AttributeError: 'str' object has no attribute 'timestamp'

Any idea on what am i doing wrong ? it seems maybe that

**Comment by shauntarves** [comment]
Hi @svanhoutte,

That method accepts a python datetime object, like this:
```
client.scales.get_records(start_time=datetime.now(), end_time=datetime.now()-timedelta(days=60)
```
