### ISSUE TITLE
Cryptodome not installed when it is.

### ISSUE THREAD

**Issue by stevenwbuehler** [shauntarves/wyze-sdk#97]
This is under Python 3.10.
```
steven@HP15:~$ pip3 list
Package                Version
---------------------- -------------
pycryptodome           3.15.0
wyze-sdk               1.6.0

steven@HP15:~$ python3 dowyze.py 
Traceback (most recent call last):
  File "/home/steven/dowyze.py", line 2, in <module>
    from wyze_sdk import Client
  File "/home/steven/.local/lib/python3.10/site-packages/wyze_sdk/__init__.py", line 3, in <module>
    from .api import Client  # noqa
  File "/home/steven/.local/lib/python3.10/site-packages/wyze_sdk/api/__init__.py", line 1, in <module>
    from .client import Client  # noqa
  File "/home/steven/.local/lib/python3.10/site-packages/wyze_sdk/api/client.py", line 4, in <module>
    from wyze_sdk.api.base import BaseClient
  File "/home/steven/.local/lib/python3.10/site-packages/wyze_sdk/api/base.py", line 6, in <module>
    from wyze_sdk.service import (ApiServiceClient, EarthServiceClient,
  File "/home/steven/.local/lib/python3.10/site-packages/wyze_sdk/service/__init__.py", line 1, in <module>
    from .api_service import ApiServiceClient  # noqa
  File "/home/steven/.local/lib/python3.10/site-packages/wyze_sdk/service/api_service.py", line 12, in <module>
    from wyze_sdk.signature import RequestVerifier
  File "/home/steven/.local/lib/python3.10/site-packages/wyze_sdk/signature/__init__.py", line 3, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'
```

**Comment by shauntarves** [comment]
Hey @stevenwbuehler,

I specifically declare `pycryptodomex` (note the `x` at the end) in the `Pipfile`. I don't know too much about these modules, but it does appear that the `pycryptodomex` dependency calls its modules the same as the other `pycryptodome` library.

Maybe give that a shot?

**Comment by stevenwbuehler** [comment]
That worked. There is also a module called `pycrytodome` (without the `x` at the end), so you may to include in your install instructions the correct module to install. :-) Thanks for your quick help!
